/**
 * load-blog-registry.ts
 *
 * blog-registry.js declares `var DRS_BLOG_POSTS = [...]` as a plain
 * browser global (auto-generated by Blog Admin, "do not edit by hand").
 * Same VM-sandbox approach as load-site-config.ts so the build step reads
 * the real generated file instead of a duplicated copy.
 */

import fs from "fs";
import path from "path";
import vm from "vm";

export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  /** Human-readable date as generated by Blog Admin, e.g. "July 1, 2026" */
  date: string;
  readTime: string;
  tags: string[];
}

export function loadBlogRegistry(
  registryPath = path.join(__dirname, "..", "blog-registry.js")
): BlogPost[] {
  const src = fs.readFileSync(registryPath, "utf-8");
  const sandbox: { DRS_BLOG_POSTS?: BlogPost[] } = {};
  vm.createContext(sandbox);
  vm.runInContext(src, sandbox, { filename: registryPath });

  if (!sandbox.DRS_BLOG_POSTS) {
    throw new Error(
      `DRS_BLOG_POSTS not found after evaluating ${registryPath}. ` +
        `Check that the file still declares "var DRS_BLOG_POSTS = [...]".`
    );
  }
  return sandbox.DRS_BLOG_POSTS;
}

/**
 * Converts the registry's human-readable date ("July 1, 2026") to an ISO
 * date (YYYY-MM-DD) for sitemap <lastmod> and Article JSON-LD. Returns
 * undefined if the string can't be parsed, so callers can omit the field
 * rather than emit a bad date.
 */
export function toIsoDate(humanDate: string): string | undefined {
  const parsed = new Date(humanDate);
  if (isNaN(parsed.getTime())) return undefined;
  return parsed.toISOString().slice(0, 10);
}
